#  Zenlayer.com Inc.
#  Copyright (c) 2014-2023 All Rights Reserved.


CREDENTIAL_MISSING_ERROR = "CREDENTIAL_VALUE_MISSING"

SDK_INVALID_REQUEST = "SDK_INVALID_REQUEST"

REQUEST_LIMIT_EXCEEDED = "REQUEST_LIMIT_EXCEEDED"
